# Generated by Django 5.2.12 on 2026-04-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("spt", "SPT"),
                            ("lpt", "LPT"),
                            ("edd", "EDD"),
                            ("johnson", "Johnson"),
                            ("cds", "CDS"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "objective",
                    models.CharField(
                        choices=[
                            ("minimize_cmax", "Minimize Cmax"),
                            ("minimize_tardiness", "Minimize Tardiness"),
                            ("balance_load", "Balance Load"),
                        ],
                        default="minimize_cmax",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("launched_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("cmax_minutes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "total_flow_time_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "average_tardiness_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Schedule run",
                "verbose_name_plural": "Schedule runs",
                "ordering": ["-created_at"],
            },
        ),
    ]
