# Generated by Django 5.2.12 on 2026-04-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulerun",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="schedulerun",
            name="gantt_data",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="schedulerun",
            name="job_sequence",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="schedulerun",
            name="jobs",
            field=models.ManyToManyField(
                blank=True, related_name="schedule_runs", to="jobs.job"
            ),
        ),
        migrations.AddField(
            model_name="schedulerun",
            name="result_metrics",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
