# Generated by Django 5.2.12 on 2026-04-05 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "machine_type",
                    models.CharField(
                        choices=[
                            ("cutting", "Cutting"),
                            ("drilling", "Drilling"),
                            ("milling", "Milling"),
                            ("turning", "Turning"),
                            ("assembly", "Assembly"),
                            ("painting", "Painting"),
                            ("packaging", "Packaging"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "workstation_number",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "capacity_per_day",
                    models.PositiveIntegerField(
                        default=480,
                        help_text="Available production time in minutes per day.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Machine",
                "verbose_name_plural": "Machines",
                "ordering": ["workstation_number", "code"],
            },
        ),
    ]
